// code/astro/src/lib/components/svelte-todos/addItem.svelte
<script lang="ts">
  import { tap } from 'rxjs'
  import { onMount } from 'svelte'
  import { getSubject } from '~/lib/common/util'
  import { addTodo } from '~/lib/services/todolist.service'

  let inputRef: HTMLInputElement

  const submitBtn$ = getSubject<boolean>()

  const submitSub = submitBtn$
    .pipe(
      tap(() => {
        const v = inputRef?.value ?? ''
        if (v !== '') {
          addTodo(v ?? '')
          inputRef.value = ''
        }
      })
    )
    .subscribe()

  onMount(() => {
    return () => {
      submitSub.unsubscribe()
    }
  })
</script>

<header class="header">
  <h1>todos</h1>
  <form on:submit|preventDefault={() => submitBtn$.next(true)}>
    <input
      class="new-todo"
      placeholder="What needs to be done?"
      bind:this={inputRef}
      autoFocus={true}
    />
  </form>
</header>

// code/astro/src/lib/components/react-todos/addItem.tsx
import { useEffect, useRef } from "react";
import { tap } from "rxjs";
import { useSubject } from "~/lib/common/rxjs-interop-react";
import { addTodo } from "~/lib/services/todolist.service";

export default function AddItem() {
  const inputRef = useRef<HTMLInputElement>(null);
  const formSubmitForm$ = useSubject<boolean>();

  useEffect(() => {
    const formSubmitSub = formSubmitForm$.pipe(
      tap(() => {
        const v = inputRef.current?.value ?? '';
        if (v !== '' && inputRef.current) {
          addTodo(v ?? '');
          inputRef.current.value = "";
        }
      })
    ).subscribe();

    return () => {
      formSubmitSub.unsubscribe();
    };
  }, []);

  return (
    <header className="header">
      <h1>todos</h1>
      <form
        onSubmit={(e) => {
          formSubmitForm$.next(true);
          e.preventDefault();
        }}
      >
        <input
          className="new-todo"
          placeholder="What needs to be done?"
          autoFocus={true}
          ref={inputRef}
        />
      </form>
    </header>
  );
}
