// code/astro/src/lib/components/vue-todos/app.vue
<template>
  <div class="min-w-2xl">
    <List />
    <footer class="info">
      <p>
        Created by <a href="http://twitter.com/bibbynet">Bibby</a>
      </p>
      <p>
        Reference to <a href="http://todomvc.com">TodoMVC</a>
      </p>
    </footer>
  </div>
</template>

<script setup lang="ts">
import List from './list.vue';
</script>

// code/astro/src/lib/components/react-todos/app.tsx
import List from './list'

export default function App() {
  return (
    <div className='min-w-2xl'>
      <List />
      <footer className='info'>
        <p>
          Created by <a href='http://twitter.com/oscargodson'>Bibby</a>
        </p>
        <p>
          Reference to <a href='http://todomvc.com'>TodoMVC</a>
        </p>
      </footer>
    </div>
  )
}
