// code/astro/src/lib/components/svelte-todos/item.svelte
<script lang="ts">
  import { filter, tap } from "rxjs";
  import { onMount } from "svelte";
  import { getSubject } from "~/lib/common/util";
  import {
    delTodo,
    updateTodo,
    type todoType
  } from "~/lib/services/todolist.service";

  export let params: todoType;
  let inputElem: HTMLInputElement;

  const updateItemBtn$ = getSubject<boolean>();
  const destroyBtn$ = getSubject<boolean>();

  const updateItemSub = updateItemBtn$
    .pipe(
      filter(() => !!inputElem),
      tap(() => {
        const newObj = JSON.parse(JSON.stringify(params)) as todoType;
        newObj.completed = inputElem.checked;
        updateTodo(newObj);
      })
    )
    .subscribe();

  const destroySub = destroyBtn$
    .pipe(tap(() => delTodo(params.id)))
    .subscribe();

  onMount(() => {
    return () => {
      updateItemSub.unsubscribe();
      destroySub.unsubscribe();
    };
  });
</script>

<li class={params.completed ? "completed" : ""}>
  <div class="view">
    <input
      class="toggle"
      type="checkbox"
      checked={params.completed}
      on:change|preventDefault={() => updateItemBtn$.next(true)}
      bind:this={inputElem}
    />
    <label>{params.title}</label>
    <button
      on:click|preventDefault={() => destroyBtn$.next(true)}
      class="destroy"
    ></button>
  </div>
</li>

// code/astro/src/lib/components/vue-todos/item.vue
<template>
  <li :class="{ 'completed': props.completed }">
    <div class="view">
      <input class="toggle" type="checkbox" v-model="props.completed" @change.prevent="updateItemBtn$.next(true)"
        ref="inputElemRef" />
      <label>{{ props.title }}</label>
      <button @click.prevent="destroyBtn$.next(true)" class="destroy"></button>
    </div>
  </li>
</template>

<script setup lang="ts">
import { filter, tap } from "rxjs";
import { onUnmounted, ref } from "vue";
import { getSubject } from "../../../lib/common/util";
import {
  delTodo,
  updateTodo,
  type todoType
} from "../../../lib/services/todolist.service";

const params = defineProps<{ props: todoType }>();

let inputElemRef = ref<HTMLInputElement>();

const updateItemBtn$ = getSubject<boolean>();
const destroyBtn$ = getSubject<boolean>();

const updateItemSub = updateItemBtn$
  .pipe(
    filter(() => !!inputElemRef.value),
    tap(() => {
      const newObj = JSON.parse(JSON.stringify(params)) as todoType;
      newObj.completed = inputElemRef.value?.checked ?? false;
      updateTodo(newObj);
    })
  )
  .subscribe();

const destroySub = destroyBtn$
  .pipe(tap(() => delTodo(params.props.id ?? 0)))
  .subscribe();

onUnmounted(() => {
  updateItemSub.unsubscribe();
  destroySub.unsubscribe();
});
</script>
