// code/astro/src/lib/components/vue-todos/app.vue
<template>
  <div class="min-w-2xl">
    <List />
    <footer class="info">
      <p>
        Created by <a href="http://twitter.com/bibbynet">Bibby</a>
      </p>
      <p>
        Reference to <a href="http://todomvc.com">TodoMVC</a>
      </p>
    </footer>
  </div>
</template>

<script setup lang="ts">
import List from './list.vue';
</script>

// code/astro/src/lib/components/svelte-todos/app.svelte
<script lang="ts">
  import List from './list.svelte'
  // your script goes here
</script>

<div class="min-w-2xl">
  <List />
  <footer class="info">
    <p>
      Created by <a href="http://twitter.com/bibbynet">Bibby</a>
    </p>
    <p>
      Reference to <a href="http://todomvc.com">TodoMVC</a>
    </p>
  </footer>
</div>
