// code/astro/src/lib/components/vue-todos/app.vue
<template>
  <div class="min-w-2xl">
    <List />
    <footer class="info">
      <p>
        Created by <a href="http://twitter.com/bibbynet">Bibby</a>
      </p>
      <p>
        Reference to <a href="http://todomvc.com">TodoMVC</a>
      </p>
    </footer>
  </div>
</template>

<script setup lang="ts">
import List from './list.vue';
</script>

// code/astro/src/lib/components/angular-todos/app.component.ts
import { CommonModule } from "@angular/common";
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { ListComponent } from "./list.component";

@Component({
  selector: 'bb-todos',
  standalone: true,
  imports: [
    CommonModule,
    ListComponent
  ],
  template: `
    <div class="min-w-2xl">
      <bb-list />
      <footer class="info">
        <p>
          Created by <a href="http://twitter.com/bibbynet">Bibby</a>
        </p>
        <p>
          Reference to <a href="http://todomvc.com">TodoMVC</a>
        </p>
      </footer>
    </div>
  `,
  styles: `
    :host {
      display: contents;
    }
  `,
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class TodosComponent { }
